routes:

  main:
    hello:
      controller: 'App\Tcp\Controller\MainController'
      method: 'main'
    menu:
      controller: 'App\Tcp\Controller\MainController'
      method: 'menu'

  debug:
    get:
      controller: 'App\Tcp\Controller\DebugController'
      method: 'getDebug'