routes:

  main:
    hello:
      controller: 'App\Tcp\Controller\MainController'
      method: 'main'
    menu:
      controller: 'App\Tcp\Controller\MainController'
      method: 'menu'

  cli:
    input:
      middlewares: [ 'App\Tcp\Middleware\Authenticate' ]
      controller: 'App\Tcp\Controller\CommandController'
      method: 'input'

  auth:
    try:
      controller: 'App\Tcp\Controller\AuthController'
      method: 'authenticate'