routes:

  main:
    hello:
      controller: 'App\Tcp\Controller\MainController'
      method: 'main'
    menu:
      controller: 'App\Tcp\Controller\MainController'
      method: 'menu'

  debug:
    get:
      middlewares: [ 'App\Tcp\Middleware\DebugAuthenticated' ]
      controller: 'App\Tcp\Controller\DebugController'
      method: 'getDebug'

  cli:
    input:
      middlewares: [ 'App\Tcp\Middleware\DebugAuthenticated' ]
      controller: 'App\Tcp\Controller\CommandController'
      method: 'input'